spring.application.name=springboot11
server.port=8090

spring.devtools.restart.enabled=true

# Propiedades asociadas al Actuator
management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.include=health,info,beans

# Posibles valores: always never when-autorized
management.endpoint.health.show-details=always

# Posibles valores: always never when-autorized
management.endpoint.env.show-values=always


management.info.env.enabled=true
info.app.name=springboot11
info.app.version=1.0.0
info.app.description=Aplicación que demuestra el uso de las dependencias DevTools y Actuator