spring.application.name=SpringBoot60

server.port=8090

spring.ai.mistralai.api-key=${MISTRALAI_API_KEY}

# Conexion a la base de datos
spring.datasource.url=jdbc:oracle:thin:@192.168.1.70:1521/XEPDB1
spring.datasource.username=SPRINGBOOT
spring.datasource.password=SPRINGBOOT
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.ai.memory.dialect.oracle.tablename=memoria_chat

# debug=true