INSERT INTO empleados (nombre, apellido, departamento, edad) VALUES
('Ana', 'Martínez', 'Recursos Humanos', 30),
('Luis', 'Gómez', 'IT', 28),
('Carla', 'López', 'Marketing', 35),
('Pedro', 'Ruiz', 'IT', 40),
('Marta', 'Fernández', 'Contabilidad', 29),
('Ana', 'Martínez', 'IT', 30),
('Luis', 'Gómez', 'Marketing', 28),
('Carla', 'López', 'Recursos Humanos', 35),
('Pedro', 'Ruiz', 'Contabilidad', 40),
('Marta', 'Fernández', 'Marketing', 29),
('Carlos', 'García', 'IT', 32),
('Sofía', 'Pérez', 'Recursos Humanos', 30),
('Diego', 'Sánchez', 'Contabilidad', 45),
('Lucía', 'Ramírez', 'IT', 28),
('Hugo', 'Torres', 'Marketing', 35),
('Valeria', 'Flores', 'Contabilidad', 29),
('Lucas', 'Moreno', 'IT', 32),
('Camila', 'Ortega', 'Marketing', 35),
('Mateo', 'Herrera', 'Recursos Humanos', 30),
('Martina', 'Castro', 'IT', 28),
('Ana', 'Martínez', 'Contabilidad', 30),
('Luis', 'Gómez', 'IT', 28),
('Carla', 'López', 'Marketing', 35),
('Pedro', 'Ruiz', 'Marketing', 40),
('Marta', 'Fernández', 'Recursos Humanos', 29),
('Carlos', 'García', 'Contabilidad', 32),
('Sofía', 'Pérez', 'IT', 30),
('Diego', 'Sánchez', 'Marketing', 45),
('Lucía', 'Ramírez', 'Recursos Humanos', 28),
('Hugo', 'Torres', 'Contabilidad', 35);