spring.application.name=springboot14
server.port=8090

spring.devtools.restart.enabled=true

# Propiedades asociadas al Actuator
management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.include=health,info,beans

# Posibles valores: always never when-autorized
management.endpoint.health.show-details=always

# Posibles valores: always never when-autorized
management.endpoint.env.show-values=always


management.info.env.enabled=true
info.app.name=springboot14
info.app.version=1.0.0
info.app.description=Aplicación que demuestra el uso de las dependencias DevTools y Actuator

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.1.70:5432/laboratorio
spring.datasource.username=springboot
spring.datasource.password=springboot
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de la base de datos MySQL
#spring.datasource.url=jdbc:mysql://192.168.1.70:3306/springboot
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de la base de datos MySQL
#spring.datasource.url=jdbc:oracle:thin:@192.168.1.70:1521/XEPDB1
#spring.datasource.username=SPRINGBOOT
#spring.datasource.password=SPRINGBOOT
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true