services:
  estudiante-service:
    build:
      context: .
      dockerfile: ./estudiante-service/Dockerfile
    container_name: estudiante-service
    ports:
      - "8090:8090"
    networks:
      - academia-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://estudiante-service:8090/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

  curso-service:
    build:
      context: .
      dockerfile: ./curso-service/Dockerfile
    container_name: curso-service
    ports:
      - "8091:8091"
    networks:
      - academia-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://curso-service:8091/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

  matricula-service:
    build:
      context: .
      dockerfile: ./matricula-service/Dockerfile
    container_name: matricula-service
    depends_on:
      estudiante-service:
        condition: service_healthy
      curso-service:
        condition: service_healthy
    ports:
      - "8092:8092"
    networks:
      - academia-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://matricula-service:8092/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

networks:
  academia-network:
    driver: bridge