spring.application.name=curso-service

server.port=8091

spring.mongodb.uri=mongodb://admin:1234@192.168.1.71:27017/coursedb?authSource=admin

# Configuracion actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
