spring.application.name=SpringBoot65

server.port=8090

# Configuracion de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.1.71:5432/laboratorio
spring.datasource.username=laboratorio
spring.datasource.password=laboratorio

# Configuracion del vectorstore
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.table-name=conceptos_ia

# Configuracion modelo embedding
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=mxbai-embed-large