spring.application.name=SpringBoot55

server.port=8090

# spring.ai.ollama.base-url=http://192.168.1.137:11434
# spring.ai.ollama.chat.model=gpt-oss:20b
# spring.ai.ollama.chat.options.temperature=0.7
# spring.ai.ollama.chat.options.top-k=40
# spring.ai.ollama.chat.options.top-p=0.9