spring.application.name=estudiante-service

server.port=8090

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=laboratorio;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1234

# Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false