spring.application.name=SpringBoot38

server.port=8090

# Configuraci�n de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.1.70:5432/laboratorio
spring.datasource.username=springboot
spring.datasource.password=springboot
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true