spring.application.name=SpringBoot64

server.port=8090

# Conexion con la base de datos Neo4J
spring.neo4j.uri=bolt://192.168.1.71:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=12345678