spring.application.name=SpringBoot63

server.port=8090

spring.ai.mistralai.api-key=${MISTRALAI_API_KEY}

# Conexion con la base de datos Neo4J
spring.neo4j.uri=bolt://192.168.1.71:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=12345678