spring.application.name=springboot72

server.port=8090

spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.name=LabRafa-MCP-client
spring.ai.mcp.client.version=1.0.0
spring.ai.mcp.client.type=SYNC

#Habilitar la ejecución de herramientas remotas
spring.ai.mcp.client.toolcallback.enabled=true
#Habilitar el escaneo de anotaciones para descubrir herramientas
spring.ai.mcp.client.annotation-scanner.enabled=true

spring.ai.mcp.client.sse.connections.server1.url=http://192.168.1.131:8282
spring.ai.mcp.client.sse.connections.server1.sse-endpoint=/sse

spring.ai.mistralai.api-key=${MISTRALAI_API_KEY}