spring.application.name=SpringBoot59

server.port=8090

spring.ai.mistralai.api-key=${MISTRALAI_API_KEY}

# Conexion a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/laboratorio
spring.datasource.username=springboot
spring.datasource.password=1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicializacion de la tabla
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql

# debug=true