spring.application.name=SpringBoot68

server.port=8090

spring.ai.stabilityai.api-key=${STABILITYAI_API_KEY}
spring.ai.stabilityai.image.base-url=https://api.stability.ai/v1
spring.ai.stabilityai.image.options.model=stable-diffusion-xl-1024-v1-0
spring.ai.stabilityai.image.options.n=1
spring.ai.stabilityai.image.options.width=1024
spring.ai.stabilityai.image.options.height=1024
spring.ai.stabilityai.image.options.cfg-scale=7.0
spring.ai.stabilityai.image.options.steps=30
spring.ai.stabilityai.image.options.style-preset=photographic