spring.application.name=SpringBoot56

server.port=8090

spring.ai.mistralai.api-key=${MISTRALAI_API_KEY}
# spring.ai.mistralai.chat.options.model=mistral-small-latest
# spring.ai.mistralai.chat.options.temperature=0.7
# spring.ai.mistralai.chat.options.top-p=0.9