spring.application.name=springboot73

server.port=8090

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.1.71:5433/laboratorio
spring.datasource.username=preprod
spring.datasource.password=preprod
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
