spring.application.name=SpringBoot66

server.port=8090

spring.ai.mistralai.api-key=${MISTRALAI_API_KEY}

# Conexion a la base de datos
spring.datasource.url=jdbc:postgresql://192.168.1.71:5432/laboratorio
spring.datasource.username=laboratorio
spring.datasource.password=laboratorio
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicializacion de la tabla
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql

# Configuracion del vectorstore
# spring.ai.vectorstore.pgvector.index-type=HNSW
# spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
# spring.ai.vectorstore.pgvector.dimensions=1024
# spring.ai.vectorstore.pgvector.initialize-schema=true
# spring.ai.vectorstore.pgvector.table-name=conceptos_ia

# Configuracion del embedding model
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=mxbai-embed-large