spring.application.name=springboot70

# Conexion a la base de datos
spring.datasource.url=jdbc:postgresql://192.168.1.71:5433/laboratorio
spring.datasource.username=springboot
spring.datasource.password=springboot

# Opciones de base de datos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show=true

# Opciones MCP server
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.stdio=true
ai.mcp.server.name=labrafa-mcp-server
ai.mcp.server.version=1.0.0

# Desactiva el servidor web embebido
spring.main.web-application-type=none
# Desactiva el banner de Spring Boot que se imprime al iniciar. Evita que la stdout contenga cosas que no sean JSON.
spring.main.banner-mode=off
# Mantiene el patron de log por defecto pero en stderr en lugar de stdout
logging.config=classpath:logback-spring.xml