spring.application.name=matricula-service

server.port=8092

# ============================
#  DATABASE (MySQL)
# ============================
spring.datasource.url=jdbc:mysql://192.168.1.71:3306/matriculadb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# Configuracion de JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ============================
#  OPENFEIGN
# ============================
feign.client.config.default.connect-timeout=3000
feign.client.config.default.read-timeout=5000

estudiante-service.url=http://localhost:8090
curso-service.url=http://localhost:8091

# ============================
#  ACTUATOR
# ============================
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always

# ============================
#  RESILIENCE4J
# ============================
# Porcentaje de fallos para que el Circuit Breaker pase de CLOSED a OPEN.
resilience4j.circuitbreaker.instances.getStudentCB.failureRateThreshold=50
# Llamadas a tener en cuenta para calcular el porcentaje de fallos
resilience4j.circuitbreaker.instances.getStudentCB.slidingWindowSize=10
# Minimo numero de llamadas a tener en cuenta para calcular el porcentaje de fallos
resilience4j.circuitbreaker.instances.getStudentCB.minimumNumberOfCalls=10
# Numero de segundos durante el cual el circuito permanece abierto antes de comprobar el servicio
resilience4j.circuitbreaker.instances.getStudentCB.waitDurationInOpenState=5s
# Numero de llamadas de prueba permitidas en estado HALF_OPEN
resilience4j.circuitbreaker.instances.getStudentCB.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.getCourseCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.getCourseCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.getCourseCB.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.getCourseCB.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.getCourseCB.permittedNumberOfCallsInHalfOpenState=3
