spring.application.name=SpringBoot57

server.port=8090

# Configuracion de Chutes AI
chutes.ai.llm.api-key=${CHUTES_API_KEY}
chutes.ai.llm.base-url=https://llm.chutes.ai
chutes.ai.llm.uri=/v1/chat/completions
chutes.ai.llm.model=Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8
chutes.ai.llm.max_tokens=1024
chutes.ai.llm.temperature=0.5
chutes.ai.llm.n=1